### PR TITLE
Release 1.2.0

### PR DESCRIPTION
**Pull request by frol**

### CODE REVIEW

**Comment by frol** [comment]
@vamega It is ready to merge!

**Comment by frol** [comment]
@jakirkham Could you please merge this PR?

**Comment by ocefpaf** [comment]
> @vamega It is ready to merge!

It has been only 11 hours, but since I am passing by I am merging this before @vamega :wink:

**Comment by vamega** [comment]
Sorry, I was away from my computer this weekend. Glad someone else was able to merge this. Thanks!

**Pull request merged**
